version: '3.7'
services: 
  mysql-clean-quarkus:
    image: mysql:8.0
    container_name: mysql-clean-quarkus
    environment:
    - MYSQL_DATABASE=quarkus
    - MYSQL_ROOT_PASSWORD=quarkus
    - MYSQL_USER=quarkus
    - MYSQL_PASSWORD=quarkus
    ports:
    - "3306:3306"
  jaeger-all-in-one:
    image: jaegertracing/all-in-one:latest
    ports:
      - "16686:16686" # Jaeger UI
      - "14268:14268" # Receive legacy OpenTracing traces, optional
      - "4317:4317"   # OTLP gRPC receiver
      - "4318:4318"   # OTLP HTTP receiver, not yet used by Quarkus, optional
      - "14250:14250" # Receive from external otel-collector, optional
    environment:
      - COLLECTOR_OTLP_ENABLED=true